<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>DWO.master.pom</artifactId>
		<version>1.1</version>
	</parent>
  <groupId>nl.numworx.pciplayer</groupId>
  <artifactId>numworxPCIplayer</artifactId>
  <version>0.1.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Numworx PCI player</name>
  <description>player for TAO PCI</description>
  <properties>
    <maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
    <tao.version>${maven.build.timestamp}</tao.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <build>
  	<finalName>${project.artifactId}-${project.version}-${tao.version}</finalName>
    <resources>
    	<resource>
    		<directory>src/main/resources</directory>
    		<filtering>true</filtering>
    	</resource>   
    </resources>
  	<plugins>
     <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>parse-version</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>parse-version</goal>
            </goals>
            <configuration>
            	<propertyPrefix>version</propertyPrefix>
            </configuration>
          </execution>
        </executions>
      </plugin>    
  	    <plugin>
  	    	<artifactId>maven-resources-plugin</artifactId>
  	    	<version>3.1.0</version>
  	    	<executions>
  	    		<execution>
  	    			<phase>package</phase>
  	    			<goals><goal>resources</goal></goals>
  	    		</execution>
  	    	</executions>
  	    </plugin>
  		<plugin>
			<artifactId>maven-assembly-plugin</artifactId>
        	<configuration>
          		<descriptors>
					<descriptor>src/main/assembly/assembly.xml</descriptor>
          		</descriptors>
        	</configuration>
            <executions>
          		<execution>
            		<id>make-assembly</id>
            		<phase>package</phase>
            		<goals>
              			<goal>single</goal>
            		</goals>
          		</execution>
        	</executions>  		
  		</plugin>
   			<plugin>
            	<groupId>external.atlassian.jgitflow</groupId>
            	<artifactId>jgitflow-maven-plugin</artifactId>
            	<version>1.0-m5.1</version>
        	</plugin>
  	</plugins>
  </build>
  <organization>
  	<name>Numworx</name>
  	<url>http://www.numworx.nl/</url>
  </organization>
  <scm>
  	<developerConnection>scm:git:git@git.science.uu.nl:dwoproject/DWO-LMS/pciplayer.git</developerConnection>
  </scm>
</project>